%% FitResult Reference
% The `FitResult` class stores model fitting outputs generated by
% `Analysis.RunAnalysisForNeuron` and `Analysis.RunAnalysisForAllNeurons`.
%
% This reference page is generated from the canonical runtime class:
%
% * <../FitResult.m FitResult.m>
%
% Related pages:
%
% * <FitResultExamples.html FitResult Examples>
% * <Analysis.html Analysis Reference>
% * <PaperOverview.html Paper-Aligned Toolbox Map>
